// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gfqwoqrcjxusedstikuo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdmcXdvcXJjanh1c2Vkc3Rpa3VvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ5Nzc1NzgsImV4cCI6MjA5MDU1MzU3OH0.ypQ6YdgOpEwdy0wuMhJsMoi6VmGjJEk8H27NQpmFf8I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});